### ISSUE TITLE
Create Timer

### ISSUE THREAD

**Issue by XUEHUANG521** [UQdeco2800/2021-studio-7#23]
# Description
**Task**: Creating Timer screen
**Feature**: MainGame/Win/Lose Transitions for the Game Loop #7
Initialise and display at the `MainMenuScreen`. Time passed determined in advance before the game start.
## Dependencies
- #5 
## Milestones
- [x] Initialise `Timer` class.
- [x] Settle down countDown feature.
## Documentation
[Timer] (https://github.com/UQdeco2800/2021-studio-7/wiki/Timer)
## Members
- Xue Huang(@XUEHUANG521 )

**Comment by tweeeb** [comment]
Hi guys! This is Treff from team 2 (interactable objects). Is the timer merged into main? And if so, what class is it in so I can access it? I would like to append a eventListener so that when the countdown reaches zero, the end game screen is called thanks :)

**Comment by XUEHUANG521** [comment]
> Hi guys! This is Treff from team 2 (interactable objects). Is the timer merged into main? And if so, what class is it in so I can access it? I would like to append a eventListener so that when the countdown reaches zero, the end game screen is called thanks :)

Hi tweeeb, the structure of timer is in /source/core/src/main/com/deco2800/game/components/maingame/MainGameTimerTestingDisplay.java
you can access timer in MainGameScreen.java. please let me know if you have any questions
