### ISSUE TITLE
Texture altars and Junit test

### ISSUE THREAD

**Issue by shiyiling1** [UQdeco2800/2021-studio-7#29]
**Task:** Create texture altars for the mom NPC and the player character and write the test for the 'PlayerAnimationController'.

**Feature:**  
-Use the Texture Packer2 to create the texture altars for the mom NPC and the player character.
-Implement a 'PlayerAnimationControllerTest' which tests the functions-"animateRunLeft,animateRunRight,animateRunUp ...." in the "PlayerAnimationController".

- [x] create the texture altars
- [x] write the test for the 'PlayerAnimationController'.

### Dependencies
- #4
- #26 
- #21

**Comment by ChanghaoXi** [comment]
Task Ticket Completion Confirmed by @ChanghaoXi
