### ISSUE TITLE
Implement female_character and Junit test

### ISSUE THREAD

**Issue by wenqi6** [UQdeco2800/2021-studio-7#30]
**Task:** Create mom entity in java. 

**Feature:**  

- Implement a `spawnMom()` which spawn random mom entity on the map.
- Implement 'MomAnimationController' which define animation and add them to an entity.
- Modify 'NPCConfigs' to add MomConfig
- Modify 'NPCFactpry' to add 'createMom()' which add animation and components to mom entity.
- Implement 'PhysicsMovementComponentTest' to test 'getCurrentDirectionCode()' and 'movementEvent()'.

- [x] Create mom entity in java
- [x] Implement test

### Dependencies
- #4
- #26 
- #21

**Comment by ChanghaoXi** [comment]
Task ticket completion confirmed by @ChanghaoXi
