### ISSUE TITLE
Main Branch Bug - Spawning entities crashes game when interacting with Mum

### ISSUE THREAD

**Issue by Luke-Cronin** [UQdeco2800/2021-studio-7#49]
### Main Branch Bug when interacting with mum causes crash

In the **ForestGameArea** class, in the **create()** method (see picture below)
![image](https://user-images.githubusercontent.com/88018796/132808852-10edc457-40f1-47dd-b197-added979ff2f.png)

### Game Crashes If:
If these following functions are called and the number of entities created within these functions are greater than 1. 
spawnTrees()
spawnGhosts()
spawnGhostKing()

If these following functions are called and the number of entities created within these functions are greater than 2. 
spawnMum()
spawnBed()
spawnPlayer()

**The game will crash when getting caught by the mum enemy/character.** 

### Game does not Crash if:
However, if these following functions are called and the number of entities created within these functions are greater than 1.
spawnTerrain();

**The game will not crash** 

### The error in the console is this:
![image](https://user-images.githubusercontent.com/88018796/132810779-20087e52-34e2-4d54-a89b-0ee6f4ae48f0.png)

**Comment by Jantoom** [comment]
It seems to happen when the PhysicsContactListener triggers a collision (either start or end of one). I tried moving the win condition to a bed collision rather than an interaction and the same bug occurs. To me, this proves that unique Mum functionality isn't the source of the problem.

I don't fully understand what you mean by the number of entities created in x functions is greater than 2. The functions you mentioned will always create 1 entity. If I called any of those functions twice, the same bug would occur. To me that puts them in the same category as the other functions.

**Comment by Jantoom** [comment]
Another note, this bug was noticed before I reverted the PhysicsContactListener in main. However, it is occurring on the reverted version as well. The bug might be deeper in the commit logs than this.

**Comment by Luke-Cronin** [comment]
> It seems to happen when the PhysicsContactListener triggers a collision (either start or end of one). I tried moving the win condition to a bed collision rather than an interaction and the same bug occurs. To me, this proves that unique Mum functionality isn't the source of the problem.
> 
> I don't fully understand what you mean by the number of entities created in x functions is greater than 2. The functions you mentioned will always create 1 entity. If I called any of those functions twice, the same bug would occur. To me that puts them in the same category as the other functions.

What I meant was that if you call the function 2 times, the bug does not occur . But it will occur if the function is called greater than 2 times (e.g. 3,4,5... but not 1 or 2 times).

**Comment by Jantoom** [comment]
> What I meant was that if you call the function 2 times, the bug does not occur . 

Interesting, I think that is the number where the bug occurs for me. I've pulled & retested and it's definitely greater than 1, not 2. Perhaps we were running different versions of main?

**Comment by Jantoom** [comment]
Fixed in [this](fa3abade553f98b7883e98f8f691880400296466) pull request.

References used for fix:
https://deco2800-2021.slack.com/archives/C01R1LVDZGU/p1629441663385300
https://www.iforce2d.net/b2dtut/removing-bodies
